name = "neontech-showcase"
main = "worker/index.ts"
compatibility_date = "2026-02-11"
pages_build_output_dir = "./dist"

[assets]
directory = "./dist"
binding = "STATIC_ASSETS"
not_found_handling = "single-page-application"
